name: Interval Crawler Task

on:
  schedule:
    - cron: '35 1,3,5,7,9,11,13,23 * * *'
  workflow_dispatch:

jobs:
  crawl-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Pull the latest data branch
        run: |
          git config user.name ZKLlab-bot
          git config user.email zkllab-bot@mail.zkllab.com
          git subtree add --prefix=interval-crawler-task-result origin data

      - name: Duplicate data folder
        run: |
          cp -r interval-crawler-task-result data

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install OpenVPN Client
        run: |
          sudo apt-get update && sudo apt-get -y install openvpn

      - name: Connect to OpenVPN
        run: |
          echo "${{ secrets.SHU_USERNAME }}" > /tmp/ovpn-auth.txt
          echo "${{ secrets.SHU_PASSWORD }}" >> /tmp/ovpn-auth.txt
          sudo openvpn --config ./shu-student.ovpn --auth-user-pass /tmp/ovpn-auth.txt --daemon

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Fetch data
        run: |
          echo "${{ secrets.SHU_PASSWORD }}" | pipenv run python crawler.py -o interval-crawler-task-result -u ${{ secrets.SHU_USERNAME }} --password-stdin

      - name: Compare, push, and create a pull request if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          pipenv run python post_crawler.py
